[package]
name = "binius_hash"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
binius_field = { path = "../field" }
binius_utils = { path = "../utils"}
bytemuck.workspace = true
cfg-if.workspace = true
digest.workspace = true
groestl_crypto.workspace = true
p3-symmetric.workspace = true
log.workspace = true

[dev-dependencies]
criterion.workspace = true
hex-literal.workspace = true
rand.workspace = true

[lib]
bench = false

[[bench]]
name = "hash"
harness = false
