[package]
name = "binius_utils"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
rayon.workspace = true
tracing.workspace = true
tracing-profile.workspace = true
tracing-subscriber.workspace = true
tracing-tracy = { workspace = true, optional = true}

[features]
tracy = ["tracing-tracy"]
